### PR TITLE
network: update calibration

### PR DESCRIPTION
**Pull request by travisperson**
Updating the calibration network information for the 2020-10-07T03:47:00Z deployment.

### CODE REVIEW

**Comment by momack2** [comment]
@pooja are you the person who can commit these?

**Review by hsanjuan — CHANGES_REQUESTED** [review]
This should be updating /static/networks/calibration.json

**Comment by hsanjuan** [comment]
It seems no one is taking care of these so I will

**Comment by hsanjuan** [comment]
(I didn't mean to sound bad, I mean the project needs better ownership in general as none of us seems to be watching often enough).

**Comment by hsanjuan** [comment]
https://github.com/filecoin-project/network-info/pull/45

**Pull request closed without merging**
